
DELETE FROM SYS_AUTHZ_ROLE_LIST;
DELETE FROM SYS_AUTHZ_USER_LIST;
DELETE FROM SYS_AUTHZ_ROLE_PERMS WHERE R_ID = '1';
DELETE FROM SYS_AUTHZ_USER_ROLE_RELATION WHERE R_ID = '1';

INSERT INTO SYS_AUTHZ_ROLE_LIST ( R_ID, R_KEY, R_NAME, R_TYPE, R_INTRO, R_STATUS)
VALUES ( '1', 'admin','超级管理员', '1', '系统初始化的最高权限用户', '1' );
INSERT INTO SYS_AUTHZ_ROLE_LIST ( R_ID, R_KEY, R_NAME, R_TYPE, R_INTRO, R_STATUS)
VALUES ( '2', 'mgr', '普通管理员', '1', '普通功能管理员', '1' );
INSERT INTO SYS_AUTHZ_ROLE_LIST ( R_ID, R_KEY, R_NAME, R_TYPE, R_INTRO, R_STATUS)
VALUES ( '3', 'normal', '普通用户', '1', '一般系统用户', '1' );

INSERT INTO SYS_AUTHZ_ROLE_PERMS ( R_ID, PERMS)
VALUES ( '1', '*');

INSERT INTO SYS_AUTHZ_USER_LIST ( U_ID, U_USERNAME, U_PASSWORD, U_SALT, U_SECRET, U_ALIAS, U_AVATAR, U_PHONE, U_EMAIL, U_BIRTHDAY, U_GENDER, U_IDCARD, U_REMARK, U_STATUS  )
VALUES ( '1', 'admin', 'YHLXHSt+CS2gJDU50amvrw==', 'MTIzNDU2', 'MTIzNDU2', '超级管理员', '','13735896863', 'jeebiz@163.com', '1989-10-01', 'male', '411526198910010001', '默认最高权限管理员', '1');

INSERT INTO SYS_AUTHZ_USER_ROLE_RELATION ( U_ID, R_ID, R_PRTY)
VALUES ( '1', '1', '0');

COMMIT;