################################################################################################################  
###Spring Boot 监控（安全、开放信息等）配置：  
################################################################################################################
management:
  endpoints:
    web:
      exposure:
        #暴露actuator的所有端点
        include: "*"  
  endpoint:
    health:
      #health endpoint是否必须显示全部细节。默认情况下, /actuator/health 是公开的，并且不显示细节
      show-details: ALWAYS

################################################################################################################  
###内置应用容器（Tomcat、Jetty、Undertow）配置：  
################################################################################################################
server:
  compression:
    enabled: true
  port: 8085
  servlet:
    context-path: /admin
    session:
      timeout: 60m
  undertow:
    # 访问日志配置
    accesslog:
      enabled: true
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    buffer-size: 2048
    # 是否分配的直接内存(NIO直接分配的堆外内存)
    direct-buffers: true
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    # 不要设置过大，如果过大，启动项目会报错：打开文件数过多
    io-threads: 16
    # 阻塞任务线程池, 当执行类似servlet请求阻塞IO操作, undertow会从这个线程池中取得线程
    # 它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8
    worker-threads: 256
    
################################################################################################################  
###Spring 相关组件（SpringMVC、Freemarker、Session、Cache、DataSource）配置：  
################################################################################################################
spring:
  application:
    name: jeebiz-boot-admin
  # 服务监控配置：
  boot:
    admin:
      monitor:
        connect-timeout: 5000
      ui:
        title: Jeebiz Boot Admin
        brand: <img src="assets/img/icon-spring-boot-admin.svg"><span>Jeebiz Boot Admin</span>
      notify:
        dingtalk:
          enabled: true
          webhook-token: https://oapi.dingtalk.com/robot/send?access_token=xxxxx
          title: 微服务运行异常警告
  jmx:
    default-domain: admin
        
  #配置登录名，密码和安全策略
  profiles:
    active:
    - insecure
  security:
    user:
      name: admin
      password: 123456
  
  # 会话配置（交个Shiro管理，此处不再指定）：
  #session: 
    #store-type: none 
      
################################################################################################################  
###logging (log4j2) 基本配置：  
###http://www.cnblogs.com/yhtboke/p/Mybatis.html
################################################################################################################
logging: 
  config: classpath:conf/log4j2-dev.xml