################################################################################################################  
###接口文档（Swagger UI）配置：  
################################################################################################################
swagger:
  enabled: true

################################################################################################################
###  微信公众号/服务号/小程序配置：
################################################################################################################
wx:
  mp:
    # 微信公众号的appid.
    app-id: wxd7a551466a0cfa03
    # 微信公众号的app secret.
    secret: eebf73aad462dab6bbdd8233919cb1a4
    # 配置存储
    config-storage:
      type: memory
  miniapp:
    # 微信小程序的appid.
    appid: wx3adb4a5ef9f61e3f
    # 微信小程序的Secret.
    secret: ebdfd09d80d8f1f23d260b7465dc69f5
    # 消息格式，XML或者JSON.
    msg-data-format: JSON

################################################################################################################
###  钉钉微应用/小程序配置
################################################################################################################
dingtalk:
  #  钉钉机器人
  robot:
    prefix: https://oapi.dingtalk.com/robot/send
    access-token: cff461c7329810b4470df80a955899f6e862187064b2d6fadf7ed569eb54a143
    secret:
      secret-enabled: true
      secret-token: SEC5102909678cc177cd486c8634029e93382c5f8620895f86ad8d9458cdb28d1a5
  # 知乎者也下的配置
  corp-id: ding5e6b33e760fd296b35c2f4657eb6378f
  crop-apps:
   # 智慧考勤小程序
  - agent-id: 589383556
    app-key: dingx0rblvppiurvk4xy
    app-secret: _8y3Vgjk1iigMQZc3_bXR__vIIxQVludc3yZ6jo0tX6Ug2cD8cMG-0iRtURcrGaI
  # 智慧考勤H5微应用
  - agent-id: 589481741
    app-key: dingxhppjmnh508naskv
    app-secret: mqFoxuq0XT6XisFkDTOc13tG1B_ESFhCXUwenqsWDVrcp32pPWXUpyepXQwnHfg92

################################################################################################################  
###Pac4j 第三方登录（QQ、微信、易班、康赛）配置：  
################################################################################################################
pac4j:
  enabled: true
  default-client-name: cas
  callback-url: http://172.16.88.245:8088/jeebiz-authz/authz/login/pac4j?client_name=cas&proxy=false
  callback-url-fixed: false
  client-parameter-name: client_name
  clients: cas
  logout:
    path-pattern: /**/logout/pac4j
    default-url: http://172.16.88.248/#/login
  cas:
    enabled: false
    accept-any-proxy: true
    gateway: false
    login-url: http://10.30.186.104/sso/login
    logout-url: http://10.30.186.104/sso/logout
    prefix-url: http://10.30.186.104/sso/
    protocol: cas20-proxy
    renew: false
    service-url: http://172.16.88.245:8088/jeebiz-authz
    # Cas客户端配置
    #cas-client: true
    #cas-client-name: cas
    # Cas代理客户端配置
    direct-cas-client: true
    direct-cas-client-name: cas
    #direct-cas-proxy-client: true
    #direct-cas-proxy-client-name: cas-proxy    

################################################################################################################  
###Spring Boot 相关组件（SpringMVC、Freemarker、Session、Cache、DataSource）配置：  
################################################################################################################
spring: 
  # 数据源配置：
  datasource:
    name: jeebiz_admin
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.123.43:3306/jeebiz_admin?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: jeebiz_admin
    password: APx37E5xPWA3Gd86
  # Redis相关配置
  redis:
    # Redis服务器地址  
    host: 47.98.123.43
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空） 
    password: HycBsP5cSp3enyGw

################################################################################################################  
###Flyway (FlywayMigrationProperties) 数据库迁移脚本版本管理（实现软件版本升级数据库自动升级）配置：  
################################################################################################################
  flyway: 
    enabled: true
    moduleable: true

################################################################################################################  
###jpush基本配置：  
################################################################################################################
jpush:
  master-secret: fd91234d9648f655e1234c1b
  app-key: 45ab34237527f342b823456b  
  production: false
    
################################################################################################################
### Filestore存储服务（FastDFS、MinIO） 基本配置：
################################################################################################################
# FastDFS
fdfs:
  enabled: true
  endpoint: http://180.76.120.252:8089
  secret-key: 6fGkkBwRnaDjfXdh
  expire: 900
  connect-timeout: 60000
  so-timeout: 60000
  tracker-list:
    - 180.76.120.252:22122
# 存储类型配置
file:
  # 指定存储配置
  storage: fdfs
    
################################################################################################################  
###阿里云服务配置：  
###https://github.com/AliwareMQ/mq-demo
################################################################################################################  
alibaba:
  cloud:
    access-key: xasdas
    secret-key: xxas
    oss:
      enabled: true
      authorization-mode: ak-sk
      access-key: 
      secret-key: 
      bucket: https://bucket.oss-accelerate.aliyuncs.com
      bucket-name: bucket
      endpoint: https://oss-cn-hangzhou.aliyuncs.com  
    ons:
      access-key: xxxxx
      secret-key: xxxxxx
      name-srv-addr: http://xxxxx.mq-internet-access.mq-internet.aliyuncs.com:80
      message-model: CLUSTERING
      group-id: GID_LAN
    sms:
        enable: true
        signs:
        - Jeebiz
  
################################################################################################################  
###腾讯云服务配置：  
###https://cloud.tencent.com/document/product/269/1520
################################################################################################################  
tencent:
  tim:
    enabled: true
    sdkappid: 22232312323
    private-key: xxx
  sms:
    enabled: true
    sdkappid: 1400006666
    secret-id: sss
    secret-key: ssss
  
################################################################################################################  
###logging (log4j2) 基本配置：  
###http://www.cnblogs.com/yhtboke/p/Mybatis.html
################################################################################################################
logging: 
  config: classpath:conf/log4j2-dev.xml
