################################################################################################################
###接口文档（Swagger UI）配置：
################################################################################################################
swagger:
  enabled: true

################################################################################################################
###Spring Boot 相关组件（SpringMVC、Freemarker、Session、Cache、DataSource）配置：
################################################################################################################
spring:
  # 缓存配置：
  cache:
    type: none  #现在改为none
  # 数据源配置：
  datasource:
    name: jeebiz_admin
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.54.2.213:3306/jeebiz_admin?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: jeebiz_admin
    password: 5RcLHz6E3AS5LFDh
  # Redis相关配置
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Database 索引；和其他服务区别开
    #database: 1
    # Redis服务器连接密码（默认为空）
    #password: HycBsP5cSp3enyGw

################################################################################################################
###Flyway (FlywayMigrationProperties) 数据库迁移脚本版本管理（实现软件版本升级数据库自动升级）配置：
################################################################################################################
  flyway:
    enabled: true
    moduleable: true

################################################################################################################
###logging (log4j2) 基本配置：
###http://www.cnblogs.com/yhtboke/p/Mybatis.html
################################################################################################################
logging:
  config: classpath:conf/log4j2-dev.xml
