################################################################################################################
###接口文档（Swagger UI）配置：
################################################################################################################
swagger:
  enabled: true

################################################################################################################
###  微信公众号/服务号/小程序配置：
################################################################################################################
wx:
  mp:
    # 微信公众号的appid.
    app-id: wx132465798
    # 微信公众号的app secret.
    secret: xxxxxxxx
    # 配置存储
    config-storage:
      type: memory
  miniapp:
    # 微信小程序的appid.
    appid: wx132465798
    # 微信小程序的Secret.
    secret: xxxxxxxxxx
    # 消息格式，XML或者JSON.
    msg-data-format: JSON

################################################################################################################
###  钉钉微应用/小程序配置
################################################################################################################
dingtalk:
  #  钉钉机器人
  robot:
    prefix: https://oapi.dingtalk.com/robot/send
    access-token: ding5455151545454545454545
    secret:
      secret-enabled: true
      secret-token: ding5455151545454545454545
  # 知乎者也下的配置
  corp-id: ding5455151545454545454545
  crop-apps:
    # 小程序
    - agent-id: 132465798
      app-key: xxxx32333333
      app-secret: _8y3Vgjk1iigMQZc3_bXR__vIIxQVludc3yZ6jo0tX6Ug2cD8cMG-0iRtURcrGaI
    # H5微应用
    - agent-id: 132465798
      app-key: xxxx32333333
      app-secret: mqFoxuq0XT6XisFkDTOc13tG1B_ESFhCXUwenqsWDVrcp32pPWXUpyepXQwnHfg92

################################################################################################################
###Pac4j 第三方登录（QQ、微信）配置：
################################################################################################################
pac4j:
  enabled: true
  default-client-name: cas
  callback-url: http://127.0.0.1:8088/jeebiz-authz/authz/login/pac4j?client_name=cas&proxy=false
  callback-url-fixed: false
  client-parameter-name: client_name
  clients: cas
  logout:
    path-pattern: /**/logout/pac4j
    default-url: http://127.0.0.1/#/login

################################################################################################################
###Spring Boot 相关组件（SpringMVC、Freemarker、Session、Cache、DataSource）配置：
################################################################################################################
spring:
  # 数据源配置：
  datasource:
    name: jeebiz_admin
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.54.2.213:3306/jeebiz_admin?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: jeebiz_admin
    password: 5RcLHz6E3AS5LFDh
  # Redis相关配置
  redis:
    # Redis服务器地址
    host: 106.54.2.213
    # Redis服务器连接端口
    port: 6379
    # Database 索引；和其他服务区别开
    #database: 1
    # Redis服务器连接密码（默认为空）
    password: HycBsP5cSp3enyGw

################################################################################################################
###Flyway (FlywayMigrationProperties) 数据库迁移脚本版本管理（实现软件版本升级数据库自动升级）配置：
################################################################################################################
  flyway:
    enabled: true
    moduleable: true

################################################################################################################
###logging (log4j2) 基本配置：
###http://www.cnblogs.com/yhtboke/p/Mybatis.html
################################################################################################################
logging:
  config: classpath:conf/log4j2-dev.xml
