################################################################################################################  
###接口文档（Swagger UI）配置：  
################################################################################################################
swagger:
  enabled: true

################################################################################################################
###  微信公众号/服务号/小程序配置：
################################################################################################################
wx:
  mp:
    # 微信公众号的appid.
    app-id: wxd7a551466a0cfa03
    # 微信公众号的app secret.
    secret: eebf73aad462dab6bbdd8233919cb1a4
    # 配置存储
    config-storage:
      type: memory
  miniapp:
    # 微信小程序的appid.
    appid: wx3adb4a5ef9f61e3f
    # 微信小程序的Secret.
    secret: ebdfd09d80d8f1f23d260b7465dc69f5
    # 消息格式，XML或者JSON.
    msg-data-format: JSON

################################################################################################################  
###Spring Boot 相关组件（SpringMVC、Freemarker、Session、Cache、DataSource）配置：  
################################################################################################################
spring: 
  # 缓存配置：
  cache: 
    type: none  #现在改为none,使用j2cache 去配置
    ehcache: 
      config: classpath:/conf/ehcache/ehcache.xml
  # 数据源配置：
  datasource:
    name: jeebiz_admin
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.54.2.213:3306/jeebiz_admin?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: jeebiz_admin
    password: 5RcLHz6E3AS5LFDh
  # Redis相关配置
  redis:
    # Redis服务器地址  
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Database 索引；和其他服务区别开
    #database: 1
    # Redis服务器连接密码（默认为空） 
    #password: HycBsP5cSp3enyGw

################################################################################################################  
###Flyway (FlywayMigrationProperties) 数据库迁移脚本版本管理（实现软件版本升级数据库自动升级）配置：  
################################################################################################################
  flyway: 
    enabled: true
    moduleable: true
    
################################################################################################################  
###阿里云服务配置：  
###https://github.com/AliwareMQ/mq-demo
################################################################################################################  
alibaba:
  cloud:
    access-key: xasdas
    secret-key: xxas
    oss:
      authorization-mode: ak-sk
      endpoint: https://oss-cn-hangzhou.aliyuncs.com  

################################################################################################################  
###logging (log4j2) 基本配置：  
###http://www.cnblogs.com/yhtboke/p/Mybatis.html
################################################################################################################
logging: 
  config: classpath:conf/log4j2-dev.xml
